<?php
$language   = $this->config['language'];

?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    作品管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('admin/works/index') ?>">作品</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> 列表(<?php echo $this->total ?>)
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="widget-body">
                    <div class="table-toolbar">
                        <a id="editabledatatable_new" href="<?php echo \Bootstrap::getUrl('admin/works/replace') ?>"
                           class="btn btn-default">
                            新增
                        </a>
                    </div>
                    <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                        <thead>
                        <tr role="row">
                            <th>
                                id
                            </th>
                            <th>
                                封面
                            </th>
                            <th>
                                名称
                            </th>
                            <th>
                                副标题
                            </th>
                            <th>
                                语言
                            </th>
                            <th>
                                操作
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        if ($this->workses) {
                            /* @var $v Orm\WorksModel */
                            foreach ($this->workses as $v) {
                                $works = $v->toArray();
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $works['id'] ?>
                                    </td>
                                    <td>
                                        <?php echo $works['pics'] ?>
                                    </td>
                                    <td>
                                        <?php echo $works['title'] ?>
                                        <br/>
                                        <?php echo $works['title_zh'] ?>
                                    </td>
                                    <td>
                                        <?php echo $works['subtitle'] ?>
                                    </td>
                                    <td><?php echo $language[$works['language']] ?></td>
                                    <td>
                                        <a href="<?php echo \Bootstrap::getUrl('admin/works/replace/').'/?id='.$works['id'];?>" class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i> Edit</a>
                                        <a href="<?php echo \Bootstrap::getUrl('admin/works/delete/').'/?id='.$works['id'];?>" class="btn btn-danger btn-xs delete"><i class="fa fa-trash-o"></i>
                                            Delete</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="6">
                                        <?php echo $works['details'] ?>
                                    </td>
                                </tr>

                                <?php
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
