<?php
$language = $this->config['language'];
$update   = $this->works ? true : false;

?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    作品管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('admin/works/index') ?>">作品</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> <?php if ($update) { ?> 编辑 <?php } else { ?> 新增 <?php } ?>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">

            <div class="col-lg-6">

                <form role="form" action="<?php if ($update) {
                    echo \Bootstrap::getUrl('admin/works/update');
                } else {
                    echo \Bootstrap::getUrl('admin/works/add');
                } ?>">

                    <div class="form-group">
                        <label>封面图片</label>
                        <input class="form-control" name="pics" value="<?php if ($update) {
                            echo $this->works['pics'];
                        } ?>"/>

                        <p class="help-block">作品名</p>
                    </div>
                    <div class="form-group">
                        <label>名称</label>
                        <input class="form-control" name="title" value="<?php if ($update) {
                            echo $this->works['title'];
                        } ?>"/>

                        <p class="help-block">作品名</p>
                    </div>

                    <div class="form-group">
                        <label>汉化名</label>
                        <input class="form-control" name="title_zh" value="<?php if ($update) {
                            echo $this->works['title_zh'];
                        } ?>"/>

                        <p class="help-block">汉化名</p>
                    </div>

                    <div class="form-group">
                        <label>副标题</label>
                        <input class="form-control" name="subtitle" value="<?php if ($update) {
                            echo $this->works['subtitle'];
                        } ?>"/>

                        <p class="help-block">副标题</p>
                    </div>


                    <div class="form-group">
                        <label>语言</label>
                        <select class="form-control" name="language">
                            <option value="0">请选择</option>
                            <?php
                            foreach ($language as $id => $name) {
                                ?>
                                <option
                                    value="<?php echo $id ?>"<?php if ($update && $this->works['language'] == $id) { ?> selected<?php } ?> ><?php echo $name ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>简介</label>
                        <textarea class="form-control" name="detail" rows="3">
                            <?php
                            if ($update) {
                                echo $this->works['details'];
                            }
                            ?>
                        </textarea>
                    </div>

                    <input type="hidden" name="id" value="<?php if ($update) {
                        echo $this->works['id'];
                    } ?>"/>
                    <button type="submit" class="btn btn-default">提交</button>
                    <button type="reset" class="btn btn-default">取消</button>

                </form>

            </div>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
