<?php
$country = $this->config['country'];
$sex     = $this->config['sex'];
$update  = $this->author ? true : false;
?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    作者管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('admin/author/index') ?>">作者</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> <?php if ($update) { ?> 编辑 <?php } else { ?> 新增 <?php } ?>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">

            <div class="col-lg-6">

                <form role="form" action="<?php if ($update) {
                    echo \Bootstrap::getUrl('admin/author/update');
                } else {
                    echo \Bootstrap::getUrl('admin/author/add');
                } ?>">

                    <div class="form-group">
                        <label>名字</label>
                        <input class="form-control" name="name" value="<?php if ($update) {
                            echo $this->author['name'];
                        } ?>"/>

                        <p class="help-block">作者名</p>
                    </div>

                    <div class="form-group">
                        <label>别名</label>
                        <input class="form-control" name="alias" value="<?php if ($update) {
                            echo $this->author['alias'];
                        } ?>"/>

                        <p class="help-block">别名</p>
                    </div>


                    <div class="form-group">
                        <label>性别</label>
                        <select class="form-control" name="sex">
                            <option value="0">请选择</option>
                            <?php
                            foreach ($sex as $id => $name) {
                                ?>
                                <option
                                    value="<?php echo $id ?>" <?php if ($update && $this->author['sex'] == $id) { ?> selected<?php } ?> ><?php echo $name ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>国家</label>
                        <select class="form-control" name="country">
                            <option value="0">请选择</option>
                            <?php
                            foreach ($country as $id => $name) {
                                ?>
                                <option
                                    value="<?php echo $id ?>" <?php if ($update && $this->author['country'] == $id) { ?> selected<?php } ?> ><?php echo $name ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>

                    <input type="hidden" name="id" value="<?php if ($update) {
                        echo $this->author['id'];
                    } ?>"/>
                    <button type="submit" class="btn btn-default">提交</button>
                    <button type="reset" class="btn btn-default">取消</button>

                </form>

            </div>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
