<?php
$works  = $this->config['works'];
?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    CP管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a
                            href="<?php echo \Bootstrap::getUrl('admin/couple/index') ?>">Couple</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> 列表(<?php echo $this->total ?>)
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="widget-body">
                    <div class="table-toolbar">
                        <a id="editabledatatable_new" href="<?php echo \Bootstrap::getUrl('admin/couple/replace') ?>"
                           class="btn btn-default">
                            新增
                        </a>
                    </div>
                    <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                        <thead>
                        <tr role="row">
                            <th>
                                名字
                            </th>
                            <th>
                                作品
                            </th>


                            <th>
                                操作
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        if ($this->couple) {
                            /* @var $v Orm\CoupleModel */
                            foreach ($this->couple as $v) {
                                $couple = $v->toArray();
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $couple['name'] ?>

                                    </td>
                                    <td><?php echo $works[$couple['works_id']] ?></td>
                                    <td>
                                        <a href="<?php echo \Bootstrap::getUrl('admin/couple/replace/') . '/?id=' . $couple['id']; ?>"
                                           class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i> Edit</a>
                                        <a href="<?php echo \Bootstrap::getUrl('admin/couple/delete/') . '/?id=' . $couple['id']; ?>"
                                           class="btn btn-danger btn-xs delete"><i class="fa fa-trash-o"></i>
                                            Delete</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3">
                                        <?php echo $couple['details'] ?>
                                    </td>
                                </tr>
                                <?php
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
