<?php
$works = $this->config['works'];
$update   = $this->couple ? true : false;

?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    couple管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('admin/couple/index') ?>">Couple</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> <?php if ($update) { ?> 编辑 <?php } else { ?> 新增 <?php } ?>
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">

            <div class="col-lg-6">

                <form role="form" action="<?php if ($update) {
                    echo \Bootstrap::getUrl('admin/couple/update');
                } else {
                    echo \Bootstrap::getUrl('admin/couple/add');
                } ?>">

                    <div class="form-group">
                        <label>CP名</label>
                        <input class="form-control" name="name" value="<?php if ($update) {
                            echo $this->couple['name'];
                        } ?>"/>

                        <p class="help-block">Cp名</p>
                    </div>


                    <div class="form-group">
                        <label>作品</label>
                        <select class="form-control" name="works_id">
                            <option value="0">请选择</option>
                            <?php
                            foreach ($works as $id => $name) {
                                ?>
                                <option
                                    value="<?php echo $id ?>"<?php if ($update && $this->couple['works_id'] == $id) { ?> selected<?php } ?> ><?php echo $name ?></option>
                                <?php
                            }
                            ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>简介</label>
                        <textarea class="form-control" name="detail" rows="3">
                            <?php
                            if ($update) {
                                echo $this->couple['details'];
                            }
                            ?>
                        </textarea>
                    </div>

                    <input type="hidden" name="id" value="<?php if ($update) {
                        echo $this->couple['id'];
                    } ?>"/>
                    <button type="submit" class="btn btn-default">提交</button>
                    <button type="reset" class="btn btn-default">取消</button>

                </form>

            </div>

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
