<?php
$graduation = $this->config['graduation'];
$language   = $this->config['language'];
$couples    = $this->config['couples'];
$authors    = $this->config['authors'];
$works      = $this->config['workses'];
?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    本子管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a href="<?php echo \Bootstrap::getUrl('admin/books/index') ?>">本子</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> 列表(<?php echo $this->total ?>)
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="widget-body">
                    <div class="table-toolbar">
                        <a id="editabledatatable_new" href="<?php echo \Bootstrap::getUrl('admin/books/replace') ?>"
                           class="btn btn-default">
                            新增
                        </a>
                    </div>
                    <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                        <thead>
                        <tr role="row">
                            <th>
                                名称
                            </th>
                            <th>
                                cp
                            </th>
                            <th>
                                作者
                            </th>
                            <th>
                                作品
                            </th>
                            <th>
                                分级
                            </th>
                            <th>
                                语言
                            </th>
                            <th>
                                操作
                            </th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php
                        if ($this->books) {
                            /* @var $v Orm\BooksModel */
                            foreach ($this->books as $v) {
                                $book = $v->toArray();
                                ?>
                                <tr>
                                    <td>
                                        <?php echo $book['title'] ?>
                                        <br/>
                                        <?php echo $book['title_ch'] ?>
                                    </td>
                                    <td><?php echo $couples[$book['couple_id']] ?></td>
                                    <td><?php echo $authors[$book['author_id']] ?></td>
                                    <td><?php echo $works[$book['works_id']] ?></td>
                                    <td><?php echo $graduation[$book['graduation']] ?></td>
                                    <td><?php echo $language[$book['language']] ?></td>
                                    <td>
                                        <a href="<?php echo \Bootstrap::getUrl('admin/books/replace/').'?id='.$book['id'];?>" class="btn btn-info btn-xs edit"><i class="fa fa-edit"></i> Edit</a>
                                        <a href="#" class="btn btn-danger btn-xs delete"><i class="fa fa-trash-o"></i>
                                            Delete</a>
                                    </td>
                                </tr>


                                <?php


                            }
                        }

                        ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
