<?php
$configs = $this->configs;

?>
<div id="page-wrapper">

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">
                    配置管理
                </h1>
                <ol class="breadcrumb">
                    <li>
                        <i class="fa fa-dashboard"></i> <a
                            href="<?php echo \Bootstrap::getUrl('admin/config/index') ?>">配置信息</a>
                    </li>
                    <li class="active">
                        <i class="fa fa-edit"></i> 列表(<?php echo $this->total ?>)
                    </li>
                </ol>
            </div>
        </div>
        <!-- /.row -->


        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="widget-body">

                    <form action="/admin/config/add" method="post">
                        <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                            <tbody>

                            <tr>
                                <td>
                                    <label><input type="text" name="typename" value=""/></label>
                                </td>
                                <td>
                                    <label><input type="text" name="typeid" value=""/></label>
                                </td>
                                <td>

                                    <label>
                                        <textarea class="form-control" name="json" rows="3">

                                        </textarea>

                                    </label>
                                </td>
                                <td>
                                    <button type="submit" class="btn btn-default">提交</button>
                                </td>

                            </tr>
                            </tbody>

                        </table>
                    </form>

                    <form action="/admin/config/update" method="post">
                        <table class="table table-striped table-hover table-bordered" id="editabledatatable">
                            <thead>
                            <tr role="row">
                                <th>
                                    id
                                </th>
                                <th>
                                    类型名
                                </th>
                                <th>
                                    类型ID
                                </th>
                                <th>
                                    详情
                                </th>
                                <th>
                                    操作
                                </th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php
                            if ($configs) {
                                /* @var $config Orm\ConfigModel */
                                foreach ($configs as $config) {
                                    $id = $config->getId();
                                    ?>

                                    <tr>

                                        <td>
                                            <?php echo $id ?>
                                        </td>
                                        <td>
                                            <label><input type="text" name="typename[<?php echo $id ?>]"
                                                          value="<?php echo $config->getTypename() ?>"/></label>
                                        </td>
                                        <td>
                                            <label><input type="text" name="typeid[<?php echo $id ?>]"
                                                          value="<?php echo $config->getTypeid() ?>"/></label>
                                        </td>
                                        <td>

                                            <label>
                                                <textarea class="form-control" name="json[<?php echo $id ?>]" rows="6" cols="40">
                                                    <?php
                                                        $desc =  !empty($config->getJson()) ? json_decode($config->getJson(),true) : [] ;
                                                        var_export($desc);
                                                    ?>
                                                </textarea>
                                            </label>
                                        </td>
                                        <td>
                                            <a data-href="<?php echo \Bootstrap::getUrl('admin/config/delete/') . '/?id=' . $config->getId(); ?>"
                                               class="btn btn-danger btn-xs delete"
                                               onclick="javascript:if (!confirm('确认要删除？')){return false;}window.location.href=$(this).data('href');"
                                            >

                                                <i class="fa fa-trash-o"></i>
                                                Delete</a>
                                        </td>

                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                            <tr>
                                <td colspan="5" style="text-align: center">
                                    <button type="submit" class="btn btn-default">提交</button>
                                </td>
                            </tr>

                            </tbody>

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->
